// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearLastFile() {
  return window['go']['main']['App']['ClearLastFile']();
}

export function Export(arg1) {
  return window['go']['main']['App']['Export'](arg1);
}

export function GetLastFile() {
  return window['go']['main']['App']['GetLastFile']();
}

export function Import(arg1) {
  return window['go']['main']['App']['Import'](arg1);
}
