// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Export(arg1) {
  return window['go']['main']['App']['Export'](arg1);
}

export function Import() {
  return window['go']['main']['App']['Import']();
}
