// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearLastFile():Promise<void>;

export function Export(arg1:string):Promise<void>;

export function GetLastFile():Promise<string>;

export function Import(arg1:string):Promise<string>;
